name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4.2.1

      - name: 🏃 Hassfest validation
        uses: home-assistant/actions/hassfest@master
        
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: With HACS Action
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v4.2.1
      - name: 🏃 HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"
